CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_Create_TB_Indices_Moedas`()
BEGIN
    DROP TEMPORARY TABLE IF EXISTS LST_TABELAS;
    DROP TEMPORARY TABLE IF EXISTS LST_CAMPOS;

    CREATE TEMPORARY TABLE LST_TABELAS (
        ID_Tabela INT PRIMARY KEY,
        Nome_Tabela VARCHAR(255),
        Nome_PK VARCHAR(255)
    );

    INSERT INTO LST_TABELAS VALUES
        ( 1, 't_alteracoes_log', 'NUM_INDEX' ),
        ( 2, 't_parametros',     'NUM_INDEX' ),
        ( 3, 't_consultas',      'NUM_INDEX' ),
        ( 4, 't_moedas',         'NUM_INDEX' ),
        ( 5, 't_cotacaomoedas',  'NUM_INDEX' ),
        ( 6, 't_moedasbrasil',   'NUM_INDEX' ),
        ( 7, 't_feriados',       '' ),
		( 8, 't_calendario',     'DataReferencia' );

    CREATE TEMPORARY TABLE LST_CAMPOS (
        ID_TabelaCampo INT PRIMARY KEY,
        Nome_DefCampo  TEXT,           
        Nome_FN_Key    TEXT            
    );

    INSERT INTO LST_CAMPOS VALUES
		( 1,
		  '`NUM_INDEX`       INT AUTO_INCREMENT NOT NULL,
		  `DATA_HORA`        DATETIME NOT NULL,
		  `NOME_TABELA`      VARCHAR(50),
		  `NOME_COLUNA`      VARCHAR(50),
		  `TP_TAM_EXISTENTE` VARCHAR(50),
		  `TP_TAM_SUGERIDO`  VARCHAR(50),
		  `MENSAGEM`         VARCHAR(255)',
		  '' ),

		( 2,
		  '`NUM_INDEX`       INT AUTO_INCREMENT NOT NULL,
		  `AnoCorrente`      INT,
		  `DataInicio_txt`   CHAR(10),
		  `DataFinal_txt`    CHAR(10),
		  `ExtensaoArquivos` CHAR(4),
		  `Idioma`           VARCHAR(10),
		  `DataInicio`       DATE NOT NULL,
		  `QtdeRegistros`    INT,
		  `URL_Padrao`       TEXT',
		  '' ),

		( 3,
		  '`NUM_INDEX`      INT AUTO_INCREMENT NOT NULL,
          `Site`            VARCHAR(100) NOT NULL,
		  `NomeConsulta`    VARCHAR(50)  NOT NULL,
		  `Complemento_URL` VARCHAR(100) NOT NULL, 
		  `Colunas`         VARCHAR(100) NOT NULL',
		  '' ),

		( 4,
		  '`NUM_INDEX` INT AUTO_INCREMENT NOT NULL, 
		  `Sigla`      VARCHAR(3)  NOT NULL, 
		  `NomeMoeda`  VARCHAR(40) NOT NULL, 
		  `TipoMoeda`  VARCHAR(1)  NOT NULL',
		  '' ),

		( 5,
		  '`NUM_INDEX`  INT AUTO_INCREMENT NOT NULL, 
		  `DataCotacao` DATE NOT NULL, 
		  `VlrCompra`   DECIMAL(8, 2), 
		  `VlrVenda`    DECIMAL(8, 2), 
		  `FK_ID_Moeda` INT',
		  'FOREIGN KEY (`FK_ID_Moeda`) REFERENCES T_Moedas(`NUM_INDEX`)' ),

		( 6,
		  '`NUM_INDEX` INT AUTO_INCREMENT NOT NULL, 
          `NomeMoeda`  VARCHAR(25), 
		  `Simbolo`    VARCHAR(4), 
		  `DataInicio` DATE NOT NULL, 
		  `DataFim`    DATE NOT NULL',
		  '' ),
          
		( 7,
		  '`NUM_INDEX`  INT          NOT NULL,
		  `Ano`         SMALLINT     NOT NULL,
		  `Mes`         TINYINT      NOT NULL,
		  `DiaMes`      TINYINT      NOT NULL,
		  `NomeFeriado` VARCHAR(150) NOT NULL,
		  `UF`          CHAR(2),
		  `TipoFeriado` ENUM(''1'', ''2'', ''3'', ''4'', ''5'') NOT NULL',
		  '' ),
          
	  	( 8,
	  	  '`NUM_INDEX`             CHAR(1)     NOT NULL, 
      	  `DataReferencia`         DATE        NOT NULL, 
	  	  `DataRef_Nome`           CHAR(10)    NOT NULL,
	  	  `Data_OffSet`            SMALLINT    NOT NULL,
	  	  `Data_Futura`            BOOLEAN     NOT NULL,
	  	  `Dia_Offset`             SMALLINT    NOT NULL,
	  	  `DiaMesRef_Nome`         CHAR(2)     NOT NULL, 
	  	  `DiaMes_Num`             TINYINT     NOT NULL,
	  	  `DiaAno_Num`             SMALLINT    NOT NULL, 
	  	  `DiaSemanaAno_Num`       SMALLINT    NOT NULL, 
	  	  `DiaSemana_Num`          TINYINT     NOT NULL, 
	  	  `DiaSemana_Abrev`        CHAR(3)     NOT NULL, 
	  	  `DiaSemana_Nome`         VARCHAR(13) NOT NULL, 
	  	  `DiaSemana_Sigla`        CHAR(1)     NOT NULL, 
	  	  `DiaUtil_Num`            BOOLEAN     NOT NULL, 
	  	  `DiaUtilMes_Acm`         TINYINT     NOT NULL, 
	  	  `DiaUtilAno_Acm`         TINYINT     NOT NULL, 
	  	  `FeriadoNome`            VARCHAR(50) DEFAULT NULL, 
	  	  `Mes_INDEX`              SMALLINT    NOT NULL, 
	  	  `Mes_Offset`             SMALLINT    NOT NULL, 
	  	  `Mes_Num`                TINYINT     NOT NULL, 
	  	  `MesRef_Nome`            CHAR(2)     NOT NULL, 
	  	  `Mes_Abrev`              CHAR(3)     NOT NULL, 
	  	  `Mes_Nome`               VARCHAR(8)  NOT NULL, 
	  	  `Mes_Sigla`              CHAR(1)     NOT NULL, 
	  	  `MesDoAno_Num`           MEDIUMINT   NOT NULL, 
	  	  `MesDoAno_Abrev`         CHAR(6)     NOT NULL, 
	  	  `MesDoAno_Nome`          CHAR(13)    NOT NULL, 
	  	  `MesDoDia_Num`           SMALLINT    NOT NULL, 
	  	  `MesDoDia_Abrev`         CHAR(6)     NOT NULL, 
	  	  `Ano_INDEX`              TINYINT     NOT NULL, 
	  	  `Ano_OffSet`             TINYINT     NOT NULL, 
	  	  `Ano_Num`                TINYINT     NOT NULL, 
	  	  `AnoRef_Nome`            CHAR(4)     NOT NULL, 
	  	  `DataAnoInicio`          DATE        NOT NULL, 
	  	  `DataAnoFim`             DATE        NOT NULL, 
	  	  `AnoFiscal`              SMALLINT    NOT NULL, 
	  	  `Semana_INDEX`           SMALLINT    NOT NULL, 
	  	  `Semana_Offset`          SMALLINT    NOT NULL, 
	  	  `SemanaRefMes_Nome`      CHAR(2)     NOT NULL, 
	  	  `SemanaDoMes_Num`        TINYINT     NOT NULL, 
	  	  `SemanaDoMes_Abrev`      CHAR(15)    NOT NULL, 
	  	  `SemanaDoAno_Num`        TINYINT     NOT NULL, 
	  	  `SemanaRefDoAno_Nome`    CHAR(2)     NOT NULL, 
	  	  `SemanaDoAno_Abrev`      CHAR(15)    NOT NULL, 
	  	  `SemanaDataInicio`       DATE        NOT NULL, 
	  	  `SemanaDataFim`          DATE        NOT NULL, 
	  	  `SemanaPeriodo`          CHAR(23)    NOT NULL, 
	  	  `Quinzena_INDEX`         SMALLINT    NOT NULL, 
	  	  `Quinzena_Offset`        SMALLINT    NOT NULL, 
	  	  `QuinzenaRefMes_Nome`    CHAR(1)     NOT NULL, 
	  	  `QuinzenaDoMes_Num`      TINYINT     NOT NULL, 
	  	  `QuinzenaDoMes_Abrev`    CHAR(9)     NOT NULL, 
	  	  `QuinzenaDoMes_Nome`     VARCHAR(14) NOT NULL, 
	  	  `QuinzenaDataInicio`     DATE        NOT NULL, 
	  	  `QuinzenaDataFim`        DATE        NOT NULL, 
	  	  `Bimestre_INDEX`         SMALLINT    NOT NULL, 
	  	  `Bimestre_Offset`        SMALLINT    NOT NULL, 
	  	  `BimestreRefAno_Nome`    CHAR(1)     NOT NULL, 
	  	  `BimestreDoAno_Num`      TINYINT     NOT NULL, 
	  	  `BimestreDoAno_Nome`     CHAR(8)     NOT NULL, 
	  	  `BimestreDataInicio`     DATE        NOT NULL, 
	  	  `BimestreDataFim`        DATE        NOT NULL, 
	  	  `BimestrePeriodo`        CHAR(23)    NOT NULL, 
	  	  `Trimestre_INDEX`        SMALLINT    NOT NULL, 
	  	  `Trimestre_Offset`       SMALLINT    NOT NULL, 
	  	  `TrimestreRefAno_Nome`   CHAR(1)     NOT NULL, 
	  	  `TrimestreDoAno_Num`     TINYINT     NOT NULL, 
	  	  `TrimestreDoAno_Nome`    CHAR(8)     NOT NULL, 
	  	  `TrimestreDataInicio`    DATE        NOT NULL, 
	  	  `TrimestreDataFim`       DATE        NOT NULL, 
	  	  `TrimestrePeriodo`       CHAR(23)    NOT NULL, 
	  	  `Semestre_INDEX`         SMALLINT    NOT NULL, 
	  	  `Semestre_Offset`        SMALLINT    NOT NULL, 
	  	  `SemestreRefAno_Nome`    CHAR(1)     NOT NULL, 
	  	  `SemestreDoAno_Num`      TINYINT     NOT NULL, 
	  	  `SemestreDoAno_Nome`     CHAR(8)     NOT NULL, 
	  	  `SemestreDataInicio`     DATE        NOT NULL, 
	  	  `SemestreDataFim`        DATE        NOT NULL, 
	  	  `SemestrePeriodo`        CHAR(23)    NOT NULL, 
	  	  `MesFechamento_INDEX`    SMALLINT    NOT NULL, 
	  	  `MesFechamento_Offset`   SMALLINT    NOT NULL, 
	  	  `MesFechamentoRef_Nome`  CHAR(2)     NOT NULL, 
	  	  `MesFechamento_Num`      TINYINT     NOT NULL, 
	  	  `MesFechamento_Abrev`    CHAR(3)     NOT NULL, 
	  	  `MesFechamento_Nome`     VARCHAR(8)  NOT NULL, 
	  	  `AnoFechamentoRef_Nome`  CHAR(4)     NOT NULL, 
	  	  `AnoFechamento_Num`      SMALLINT    NOT NULL, 
	  	  `MesAnoFechamento_Num`   MEDIUMINT   NOT NULL, 
	  	  `MesAnoFechamento_Abrev` CHAR(6)     NOT NULL, 
	  	  `EstacaoAnoNum`          TINYINT     NOT NULL, 
	  	  `EstacaoAnoNome`         CHAR(9)     NOT NULL',
	  	  '');
END